#include <stdio.h>

#define COMMAND(NAME, TYPE) TYPE##_##NAME##_command
#define DEFINE_COMMAND(NAME, TYPE) void COMMAND(NAME, TYPE) (void)

#define DEFINE_EXTERNAL_COMMAND(NAME) DEFINE_COMMAND(NAME, external)
#define DEFINE_INTERNAL_COMMAND(NAME) DEFINE_COMMAND(NAME, internal)

#define CALL_COMMAND(NAME, TYPE) COMMAND(NAME, TYPE) ()
#define CALL_EXTERNAL_COMMAND(NAME) CALL_COMMAND(NAME, external)
#define CALL_INTERNAL_COMMAND(NAME) CALL_COMMAND(NAME, internal)

int main()
{
    DEFINE_EXTERNAL_COMMAND(quit);
    DEFINE_INTERNAL_COMMAND(print);
    CALL_INTERNAL_COMMAND(quit);
    CALL_EXTERNAL_COMMAND(delete);

    return 0;
}